# Generated by Django 6.0 on 2025-12-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('date', models.DateField()),
            ],
        ),
    ]
